version: "3.4"

x-common-variables: &common-variables
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: userSystem
  REACT_APP_SERVER_PORT: 8000

services:
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/userSystem.sql:/docker-entrypoint-initdb.d/userSystem.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    volumes:
      - ./server:/app
    links:
      - mysql:mysql
    command: yarn start
  client:
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    links:
      - server
    command: yarn start
